"""
Breakout game configuration file. 
"""

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60 # Number of frames per second.

PADDLE_WIDTH = 100
PADDLE_HEIGHT = 10
PADDLE_VELOCITY = 5
BALL_WIDTH = 10
BALL_HEIGHT = 10
BALL_VELOCITY = 8


BOUNCE_LEFT_LIMIT = 0
BOUNCE_RIGHT_LIMIT = SCREEN_WIDTH-BALL_WIDTH
BOUNCE_TOP_LIMIT = 40
BOUNCE_BOTTOM_LIMIT = PADDLE_HEIGHT

GAME_TITLE = "Breakout Game"